apiVersion: v1
kind: Service
metadata:
  labels:
    app: magic-frame-caddy
  name: magic-frame-caddy
  namespace: magic-frame
spec:
  type: NodePort
  ports:
    - name: 80-tcp
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: 443-tcp
      port: 443
      nodePort: 30443
      targetPort: 443
    - name: 443-udp
      port: 443
      protocol: UDP
      targetPort: 443
    - name: "2019"
      port: 2019
      targetPort: 2019
      nodePort: 32019
  selector:
    app: magic-frame-caddy
