apiVersion: v1
kind: ConfigMap
metadata:
  name: magic-frame-env
  namespace: {{ .Values.namespace.namespace }}
  labels:
    app: magic-frame-env
data:
  ADMIN_EMAIL: {{ .Values.appConfig.adminEmail | quote }}
  ADMIN_PASSWORD: {{ .Values.appConfig.adminPassword | quote }}
  APP_BASE_URL: {{ .Values.appConfig.appBaseUrl | quote }}
  CADDY_ADMIN_URL: {{ .Values.appConfig.caddyAdminUrl | quote }}
  COOKIE_SECURE: {{ .Values.appConfig.cookieSecure | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.appConfig.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.appConfig.googleClientSecret | quote }}
  MS_CLIENT_ID: {{ .Values.appConfig.msClientId | quote }}
  MS_CLIENT_SECRET: {{ .Values.appConfig.msClientSecret | quote }}
  NODE_ENV: {{ .Values.appConfig.nodeEnv | quote }}
  OPENWEATHERMAP_API_KEY: {{ .Values.appConfig.openWeatherMapApiKey | quote }}
  SESSION_SECRET: {{ .Values.appConfig.sessionSecret | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s?schema=public" .Values.appConfig.dbUser .Values.appConfig.dbPassword .Values.appConfig.dbHost .Values.appConfig.dbPort .Values.appConfig.dbName | quote }}