apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic-frame-db
  namespace: {{ .Values.namespace.namespace }}
  labels:
    app: magic-frame-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magic-frame-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magic-frame-db
    spec:
      containers:
        - name: magic-frame-db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: {{ .Values.appConfig.dbName | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.appConfig.dbUser | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: magic-frame-secrets
                  key: DB_PASSWORD
          ports:
            - containerPort: 5432
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: magic-frame-pgdata-pvc
      restartPolicy: Always
      volumes:
        - name: magic-frame-pgdata-pvc
          persistentVolumeClaim:
            claimName: magic-frame-pgdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: magic-frame-db
  namespace: {{ .Values.namespace.namespace }}
  labels:
    app: magic-frame-db
spec:
  type: ClusterIP
  ports:
    - name: db-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: magic-frame-db