apiVersion: v1
kind: Secret
metadata:
  name: magic-frame-secrets
  namespace: {{ .Values.namespace.namespace }}
  labels:
    app: magic-frame-secrets
type: Opaque
stringData:
  # Passwords & Secrets
  ADMIN_PASSWORD: {{ .Values.appConfig.adminPassword | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.appConfig.googleClientSecret | quote }}
  MS_CLIENT_SECRET: {{ .Values.appConfig.msClientSecret | quote }}
  SESSION_SECRET: {{ .Values.appConfig.sessionSecret | quote }}
  OPENWEATHERMAP_API_KEY: {{ .Values.appConfig.openWeatherMapApiKey | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s?schema=public" .Values.appConfig.dbUser .Values.appConfig.dbPassword .Values.appConfig.dbHost .Values.appConfig.dbPort .Values.appConfig.dbName | quote }}
  DB_PASSWORD: {{ .Values.appConfig.dbPassword | quote }}