import "server-only";
import type { CaddyConfig } from "./store";
import { getDdnsConfig } from "@/lib/ddns/store";
import { getCaddyProvider } from "./providers";

/**
 * Rendert das Caddyfile aus der CaddyConfig.
 *
 * mode="custom": liefert genau das vom User reingeschriebene File zurück
 *                (ohne Validierung — die macht Caddy beim Load).
 *
 * mode="managed":
 *   - !enabled || !domain  → transparenter HTTP-Proxy auf :80, kein TLS
 *   - enabled + http       → automatisches HTTPS via HTTP-01 (Port 80 muss offen sein)
 *   - enabled + dns        → automatisches HTTPS via DNS-01 mit Provider-Plugin
 *
 * Bei DNS-01 werden Auth-Felder zuerst aus caddy.providerConfig[provider] gelesen.
 * Wenn dort leer und der Provider auch in DDNS existiert (cloudflare/hetzner),
 * holen wir ein „Auto-Fill" aus ddns.providerConfig[provider] — damit man nicht
 * den gleichen Token zweimal eintippen muss.
 */
/**
 * Adresse, unter der Caddy die App erreicht. In docker-compose heißt der
 * Service "app", auf Kubernetes je nach Namensschema anders (z. B.
 * "magic-frame-app"). Statt das Caddyfile von Hand nachzubearbeiten, kann
 * die Adresse über APP_UPSTREAM gesetzt werden — Standard bleibt app:3000,
 * bestehende Installationen merken davon nichts. (Frage von @RudiKlein, #24)
 */
function appUpstream(): string {
  const raw = (process.env.APP_UPSTREAM || "").trim();
  if (!raw) return "app:3000";
  // Nur Host[:Port] zulassen — das Caddyfile ist eine Konfigurationsdatei,
  // hier soll niemand zusätzliche Direktiven einschleusen können.
  return /^[A-Za-z0-9._-]+(:\d{1,5})?$/.test(raw) ? raw : "app:3000";
}

/**
 * A reverse_proxy block that tells the app who the client is.
 *
 * Only the managed-HTTPS block ever set these headers. Every other shape — the
 * no-domain default, the custom-mode fallback, the plain :80 listener when the
 * HTTPS redirect is off — proxied without them, and that is the shape a normal
 * LAN install runs. The app then saw no client address at all and recorded
 * every login attempt against the same placeholder, which turned the per-address
 * lockout into ONE SHARED LOCK: five wrong guesses by anybody locked the login
 * page for the whole household for half an hour.
 *
 * `{remote_host}` is the peer Caddy actually accepted the connection from, so
 * it cannot be spoofed by a header the client sends.
 */
function proxyBlock(indent = ""): string[] {
  return [
    `${indent}reverse_proxy ${appUpstream()} {`,
    `${indent}    header_up X-Real-IP {remote_host}`,
    `${indent}    header_up X-Forwarded-For {remote_host}`,
    `${indent}    header_up X-Forwarded-Proto {scheme}`,
    `${indent}}`,
  ];
}

export async function generateCaddyfile(cfg: CaddyConfig): Promise<{
  caddyfile: string;
  warnings: string[];
}> {
  const warnings: string[] = [];

  if (cfg.mode === "custom") {
    if (!cfg.customCaddyfile.trim()) {
      warnings.push("Custom-Caddyfile ist leer.");
      return {
        caddyfile:
          "# Custom-Modus, aber leeres Caddyfile — fallback auf transparenten Proxy.\n:80 {\n" +
          proxyBlock("    ").join("\n") +
          "\n}\n",
        warnings,
      };
    }
    return { caddyfile: cfg.customCaddyfile, warnings };
  }

  const lines: string[] = [];

  lines.push("# Auto-generated by Magic Frame. Manuelle Änderungen werden beim nächsten Reload überschrieben.");
  lines.push("");
  lines.push("{");
  lines.push("    admin 0.0.0.0:2019");
  if (cfg.acmeEmail) lines.push(`    email ${cfg.acmeEmail}`);
  if (!cfg.enabled || !cfg.domain) lines.push("    auto_https off");
  lines.push("}");
  lines.push("");

  if (!cfg.enabled || !cfg.domain) {
    lines.push(":80 {");
    lines.push(...proxyBlock("    "));
    lines.push("}");
    return { caddyfile: lines.join("\n") + "\n", warnings };
  }

  if (!cfg.acmeEmail) {
    warnings.push("ACME-Email fehlt — Let's Encrypt verweigert sonst die Cert-Ausstellung.");
  }

  let tlsBlock: string[] = [];
  if (cfg.challenge === "dns") {
    const provider = getCaddyProvider(cfg.dnsProvider);
    let params: Record<string, string> = { ...(cfg.providerConfig[cfg.dnsProvider] ?? {}) };

    // Auto-Fill aus DDNS wenn das Caddy-Bag leer ist und der Provider eine
    // Bridge anbietet (cloudflare/hetzner).
    const missingRequired = provider.fields
      .filter((f) => f.required)
      .some((f) => !(params[f.key] && params[f.key].length > 0));
    if (missingRequired && provider.ddnsTokenSource) {
      const ddns = await getDdnsConfig();
      const ddnsBag = ddns.providerConfig[cfg.dnsProvider as "cloudflare" | "hetzner"];
      if (ddnsBag) {
        const fill = provider.ddnsTokenSource(ddnsBag);
        for (const [k, v] of Object.entries(fill)) {
          if (v && !(params[k] && params[k].length > 0)) params[k] = String(v);
        }
      }
    }

    const stillMissing = provider.fields.filter(
      (f) => f.required && !(params[f.key] && params[f.key].length > 0),
    );
    if (stillMissing.length > 0) {
      warnings.push(
        `DNS-01 (${provider.label}) verlangt: ${stillMissing.map((f) => f.label).join(", ")}. ` +
          `Bitte in der HTTPS-Karte unter „${provider.label}" eintragen.`,
      );
      tlsBlock = []; // Caddy soll dann auf HTTP-01 fallen
    } else {
      tlsBlock = provider.tlsBlock(params);
    }
  }

  const domains = [cfg.domain, ...cfg.extraDomains].filter(Boolean).join(", ");
  lines.push(`${domains} {`);
  for (const l of tlsBlock) lines.push(`    ${l}`);
  lines.push("    encode zstd gzip");
  lines.push(...proxyBlock("    "));
  lines.push("}");

  if (!cfg.redirectHttp) {
    lines.push("");
    lines.push("# HTTP→HTTPS-Redirect deaktiviert; Caddy lauscht weiter auf :80 mit reverse_proxy.");
    lines.push(":80 {");
    lines.push(...proxyBlock("    "));
    lines.push("}");
  }

  return { caddyfile: lines.join("\n") + "\n", warnings };
}
