apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: magic-frame-app
  name: magic-frame-app
  namespace: magic-frame
spec:
  replicas: 1
  selector:
    matchLabels:
     app: magic-frame-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magic-frame-app
    spec:
      containers:
        - env:
            - name: ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_EMAIL
                  name: magic-frame-env
            - name: ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_PASSWORD
                  name: magic-frame-env
            - name: APP_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: APP_BASE_URL
                  name: magic-frame-env
            - name: CADDY_ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  key: CADDY_ADMIN_URL
                  name: magic-frame-env
            - name: COOKIE_SECURE
              valueFrom:
                configMapKeyRef:
                  key: COOKIE_SECURE
                  name: magic-frame-env
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: magic-frame-env
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: magic-frame-env
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_CLIENT_SECRET
                  name: magic-frame-env
            - name: MS_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: MS_CLIENT_ID
                  name: magic-frame-env
            - name: MS_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: MS_CLIENT_SECRET
                  name: magic-frame-env
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: magic-frame-env
            - name: OPENWEATHERMAP_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: OPENWEATHERMAP_API_KEY
                  name: magic-frame-env
            - name: SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  key: SESSION_SECRET
                  name: magic-frame-env
          image: ghcr.io/jeremiaa/magic-frame-app:latest
          name: magic-frame-app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/configs
              name: magic-frame-configs-pvc
            - mountPath: /app/wallpapers
              name: magic-frame-wallpapers-pvc
#
# Uncomment the 2 lines below if you want to run and use Caddy
# Make sure the indentation is correct.
#
#            - mountPath: /caddy/config
#              name: magic-frame-caddy-config-pvc
      restartPolicy: Always
      volumes:
        - name: magic-frame-configs-pvc
          persistentVolumeClaim:
            claimName: magic-frame-configs-pvc
        - name: magic-frame-wallpapers-pvc
          persistentVolumeClaim:
            claimName: magic-frame-wallpapers-pvc
#
# Uncomment the 3 lines below if you want to run and use Caddy.
# Make sure the indentation is correct.
#
#        - name: magic-frame-caddy-config-pvc
#          persistentVolumeClaim:
#            claimName: magic-frame-caddy-config-pvc
---

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: magic-frame-env
  name: magic-frame-env
  namespace: magic-frame
data:
  ADMIN_EMAIL: ""
  ADMIN_PASSWORD: ""
  APP_BASE_URL: ""
  CADDY_ADMIN_URL: "http://caddy:2019"
  COOKIE_SECURE: ""
  DATABASE_URL: "postgresql://postgres:postgres@magic-frame-db:5432/magicdashboard?schema=public"
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  MS_CLIENT_ID: ""
  MS_CLIENT_SECRET: ""
  NODE_ENV: "production"
  OPENWEATHERMAP_API_KEY: ""
#
# Put the generated session secret between the quotes on the line below.
#
  SESSION_SECRET: "<paste session secret here>"

