# Toggle Caddy deployment and related configs on or off
caddy:
  enabled: false

# Namespace setting
namespace:
  namespace: magic-frame

# Application Image Settings
image:
  repository: magic-frame-app
  tag: latest
  pullPolicy: Never

# nodePort Settings (external access). Change to your needs!
nodePorts:
  httpPort: 30080
  httpsPort: 30443
  caddyPort: 32019

# Environment Variables
appConfig:
  # --- Public Configuration (ConfigMap) ---
  adminEmail: ""
  appBaseUrl: ""
  caddyAdminUrl: "http://magic-frame-caddy:2019"
  cookieSecure: ""
  googleClientId: ""
  msClientId: ""
  nodeEnv: "production"

# Persistent Storage Configurations
storage:
  className: "magic-frame-storage"
  capacity: "100Mi"
  # Base path for hostPath volumes
  hostPathBase: "/var/lib/rancher/k3s/storage"

  # --- Database Configuration ---
  dbHost: "magic-frame-db"
  dbPort: "5432"
  dbName: "magicdashboard"
  dbUser: "postgres"

  # --- Sensitive Credentials (Kubernetes Secret) ---
  adminPassword: ""
  googleClientSecret: ""
  msClientSecret: ""
  openWeatherMapApiKey: ""

  sessionSecret: "GENERATED_SECRET_HERE"
  dbPassword: "YOUR_SECURE_PASSWORD_HERE"

